import { Info } from "lucide-react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogFooter,
  DialogTitle,
  DialogDescription,
  DialogClose,
} from "@/components/ui/dialog";
import type { AppLanguage } from "@/common/language/storage";

interface HomeInfoModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  lang: AppLanguage;
}

const CONTENT: Record<
  AppLanguage,
  {
    title: string;
    subtitle: string;
    intro: string;
    sections: { title: string; desc: string }[];
    closeBtn: string;
  }
> = {
  it: {
    title: "Come funziona questa pagina",
    subtitle: "Menu principale — Taratura Serbatoi",
    intro:
      "Questa è la pagina iniziale della suite: da qui si accede a tutti i moduli di calcolo per la taratura dei serbatoi.",
    sections: [
      {
        title: "Dati Comuni → Intestazione Report",
        desc: "Si compila una sola volta: ragione sociale, P.IVA, contatti, logo e note. Questi dati vengono poi usati automaticamente su tutti i certificati PDF generati da qualsiasi modulo, senza doverli reinserire ogni volta.",
      },
      {
        title: "Moduli di calcolo",
        desc: "Ogni card rappresenta una configurazione di testate (es. Coperchio Bombato / Fondo Conico). Solo i moduli contrassegnati 'Attivo' sono già utilizzabili; quelli 'In preparazione' verranno abilitati in seguito. Cliccando su un modulo attivo si apre l'applicativo completo: geometria, calcolo, tabella di calibrazione e certificato PDF.",
      },
      {
        title: "Selettore lingua",
        desc: "Il pulsante lingua in alto a destra è persistente: la lingua scelta qui viene ricordata anche quando apri un modulo, e viceversa se la cambi dentro un modulo resterà impostata anche qui al ritorno al menu.",
      },
    ],
    closeBtn: "Ho capito, chiudi",
  },
  en: {
    title: "How this page works",
    subtitle: "Main menu — Tank Calibration",
    intro:
      "This is the suite's landing page: from here you can access all the tank calibration calculation modules.",
    sections: [
      {
        title: "Common Data → Report Header",
        desc: "Fill it in once: company name, VAT number, contacts, logo and notes. This data is then automatically used on every PDF certificate generated by any module, without re-entering it each time.",
      },
      {
        title: "Calculation modules",
        desc: "Each card represents a head configuration (e.g. Dished Head / Conical Bottom). Only modules marked 'Active' are already usable; those 'In preparation' will be enabled later. Clicking an active module opens the full application: geometry, calculation, calibration table and PDF certificate.",
      },
      {
        title: "Language switcher",
        desc: "The language button in the top-right is persistent: the language chosen here is remembered when you open a module, and if you change it inside a module it stays set here too when you return to the menu.",
      },
    ],
    closeBtn: "Got it, close",
  },
  es: {
    title: "Cómo funciona esta página",
    subtitle: "Menú principal — Calibración de Tanques",
    intro:
      "Esta es la página inicial de la suite: desde aquí se accede a todos los módulos de cálculo para la calibración de tanques.",
    sections: [
      {
        title: "Datos Comunes → Encabezado del Informe",
        desc: "Se rellena una sola vez: razón social, NIF, contactos, logo y notas. Estos datos se usan automáticamente en todos los certificados PDF generados por cualquier módulo, sin necesidad de volver a introducirlos.",
      },
      {
        title: "Módulos de cálculo",
        desc: "Cada tarjeta representa una configuración de cabezales (ej. Fondo Abombado / Fondo Cónico). Solo los módulos marcados como 'Activo' ya son utilizables; los 'En preparación' se habilitarán más adelante. Al hacer clic en un módulo activo se abre la aplicación completa: geometría, cálculo, tabla de calibración y certificado PDF.",
      },
      {
        title: "Selector de idioma",
        desc: "El botón de idioma arriba a la derecha es persistente: el idioma elegido aquí se recuerda al abrir un módulo, y si lo cambias dentro de un módulo, seguirá configurado aquí al volver al menú.",
      },
    ],
    closeBtn: "Entendido, cerrar",
  },
  de: {
    title: "So funktioniert diese Seite",
    subtitle: "Hauptmenü — Behälterkalibrierung",
    intro:
      "Dies ist die Startseite der Suite: von hier aus erreichen Sie alle Berechnungsmodule für die Behälterkalibrierung.",
    sections: [
      {
        title: "Gemeinsame Daten → Berichtskopf",
        desc: "Einmal ausfüllen: Firmenname, USt-IdNr., Kontakte, Logo und Notizen. Diese Daten werden dann automatisch auf jedem PDF-Zertifikat verwendet, das von einem beliebigen Modul erzeugt wird, ohne erneute Eingabe.",
      },
      {
        title: "Berechnungsmodule",
        desc: "Jede Karte steht für eine Bodenkonfiguration (z. B. Gewölbter Deckel / Konischer Boden). Nur mit 'Aktiv' gekennzeichnete Module sind bereits nutzbar; 'In Vorbereitung' werden später freigeschaltet. Ein Klick auf ein aktives Modul öffnet die vollständige Anwendung: Geometrie, Berechnung, Kalibriertabelle und PDF-Zertifikat.",
      },
      {
        title: "Sprachauswahl",
        desc: "Die Sprachschaltfläche oben rechts ist dauerhaft: Die hier gewählte Sprache wird beim Öffnen eines Moduls übernommen, und wenn Sie sie in einem Modul ändern, bleibt sie auch hier im Menü erhalten.",
      },
    ],
    closeBtn: "Verstanden, schließen",
  },
};

export default function HomeInfoModal({ open, onOpenChange, lang }: HomeInfoModalProps) {
  const t = CONTENT[lang] ?? CONTENT.it;

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-h-[calc(100vh-4rem)] overflow-y-auto sm:max-w-lg">
        <DialogHeader>
          <div className="flex items-center gap-2">
            <Info className="h-5 w-5 text-primary" />
            <DialogTitle>{t.title}</DialogTitle>
          </div>
          <DialogDescription>{t.subtitle}</DialogDescription>
        </DialogHeader>

        <p className="rounded-xl border border-primary/20 bg-primary/5 p-4 text-sm text-foreground">
          {t.intro}
        </p>

        <div className="space-y-3">
          {t.sections.map((s) => (
            <div key={s.title} className="rounded-xl border border-border bg-card p-4">
              <h4 className="mb-1 text-sm font-semibold text-foreground">{s.title}</h4>
              <p className="text-sm text-muted-foreground">{s.desc}</p>
            </div>
          ))}
        </div>

        <DialogFooter>
          <DialogClose asChild>
            <button
              type="button"
              className="inline-flex items-center justify-center rounded-xl bg-primary px-4 py-2 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/90"
            >
              {t.closeBtn}
            </button>
          </DialogClose>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
