/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AttivazioneRouteImport } from './routes/attivazione'
import { Route as DatiComuniRouteImport } from './routes/dati-comuni'
import { Route as LicenzaScadutaRouteImport } from './routes/licenza-scaduta'
import { Route as ModuliModuleIdRouteImport } from './routes/moduli.$moduleId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AttivazioneRoute = AttivazioneRouteImport.update({
  id: '/attivazione',
  path: '/attivazione',
  getParentRoute: () => rootRouteImport,
} as any)
const DatiComuniRoute = DatiComuniRouteImport.update({
  id: '/dati-comuni',
  path: '/dati-comuni',
  getParentRoute: () => rootRouteImport,
} as any)
const LicenzaScadutaRoute = LicenzaScadutaRouteImport.update({
  id: '/licenza-scaduta',
  path: '/licenza-scaduta',
  getParentRoute: () => rootRouteImport,
} as any)
const ModuliModuleIdRoute = ModuliModuleIdRouteImport.update({
  id: '/moduli/$moduleId',
  path: '/moduli/$moduleId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attivazione': typeof AttivazioneRoute
  '/dati-comuni': typeof DatiComuniRoute
  '/licenza-scaduta': typeof LicenzaScadutaRoute
  '/moduli/$moduleId': typeof ModuliModuleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attivazione': typeof AttivazioneRoute
  '/dati-comuni': typeof DatiComuniRoute
  '/licenza-scaduta': typeof LicenzaScadutaRoute
  '/moduli/$moduleId': typeof ModuliModuleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attivazione': typeof AttivazioneRoute
  '/dati-comuni': typeof DatiComuniRoute
  '/licenza-scaduta': typeof LicenzaScadutaRoute
  '/moduli/$moduleId': typeof ModuliModuleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attivazione'
    | '/dati-comuni'
    | '/licenza-scaduta'
    | '/moduli/$moduleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attivazione'
    | '/dati-comuni'
    | '/licenza-scaduta'
    | '/moduli/$moduleId'
  id:
    | '__root__'
    | '/'
    | '/attivazione'
    | '/dati-comuni'
    | '/licenza-scaduta'
    | '/moduli/$moduleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttivazioneRoute: typeof AttivazioneRoute
  DatiComuniRoute: typeof DatiComuniRoute
  LicenzaScadutaRoute: typeof LicenzaScadutaRoute
  ModuliModuleIdRoute: typeof ModuliModuleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attivazione': {
      id: '/attivazione'
      path: '/attivazione'
      fullPath: '/attivazione'
      preLoaderRoute: typeof AttivazioneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dati-comuni': {
      id: '/dati-comuni'
      path: '/dati-comuni'
      fullPath: '/dati-comuni'
      preLoaderRoute: typeof DatiComuniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licenza-scaduta': {
      id: '/licenza-scaduta'
      path: '/licenza-scaduta'
      fullPath: '/licenza-scaduta'
      preLoaderRoute: typeof LicenzaScadutaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moduli/$moduleId': {
      id: '/moduli/$moduleId'
      path: '/moduli/$moduleId'
      fullPath: '/moduli/$moduleId'
      preLoaderRoute: typeof ModuliModuleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttivazioneRoute: AttivazioneRoute,
  DatiComuniRoute: DatiComuniRoute,
  LicenzaScadutaRoute: LicenzaScadutaRoute,
  ModuliModuleIdRoute: ModuliModuleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
